apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: mern-client
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30002
